### ISSUE TITLE
What tools do you use for point cloud visualization in this paper?

### ISSUE THREAD

**Issue by cuge1995** [itailang/geometric_adv#1]

**Comment by itailang** [comment]
Hello @cuge1995,

I used a rendering software called Mitsuba. You can find installation instructions here: https://medium.com/@sreenithyc21/10-steps-to-install-mitsuba-renderer-on-ubuntu-38a9318fbcdf.

I was also assisted by this repository: https://github.com/zekunhao1995/PointFlowRenderer. It examples how to use Mitsuba via the command line.
