### ISSUE TITLE
where is file attack_configuration.pickle?  

### ISSUE THREAD

**Issue by luogyu7** [itailang/geometric_adv#3]
When I run the command “python run_classifier.py  --data_type target --attack_folder out_space_attack”

the log:
`
Instructions for updating:
Colocations handled automatically by placer.
Run classifier flags: Namespace(ae_folder='log/autoencoder_victim', attack_folder='output_space_attack', attack_pc_idx='log/autoencoder_victim/eval/sel_idx_rand_100_test_set_13l.npy', classifier_folder='log/pointnet', classifier_restore_epoch=150, data_type='target', defense_folder='defense_critical_res', num_classes=13, num_points=2048, output_folder_name='classifier_res')
Traceback (most recent call last):
  File "run_classifier.py", line 72, in <module>
    conf = Conf.load(osp.join(classifier_data_path, 'attack_configuration'))
  File "/media/l1/Disk28/Luogyu/3D_Attack_Defense/geometric_adv/geometric_adv/src/autoencoder.py", line 82, in load
    return unpickle_data(file_name + '.pickle').__next__()
  File "/media/l1/Disk28/Luogyu/3D_Attack_Defense/geometric_adv/geometric_adv/src/in_out.py", line 63, in unpickle_data
    inFile = open(file_name, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/media/l1/Disk28/Luogyu/3D_Attack_Defense/geometric_adv/geometric_adv/log/autoencoder_victim/eval/output_space_attack/attack_configuration.pickle'`

And   I search the file name ‘attack_configuration.pickle'  ,   just have the file named 'configuration.pickle' 

Is this normal?Thanks.

**Comment by itailang** [comment]
Dear @luogyu7,

The file `attack_configuration.pickle` is saved once you run an attack, see [here](https://github.com/itailang/geometric_adv/blob/302ede4bd980b25362638c021194762659e4e3d1/attacker/run_attack.py#L109). Please run the attack first, before you run the classifier.

Let me know if you have any further questions. Thanks!
